### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by prodchia** [joaquimguimaraes/farmr#104]
I am getting following error after I tried to restart farmr . 

Unhandled exception:
type '_Smi' is not a subtype of type 'double'
#0      Blockchain._fromJson (package:farmr_client/blockchain.dart:115)
#1      new Blockchain (package:farmr_client/blockchain.dart:75)
#2      readBlockchains (file:///d:/a/farmr/farmr/farmr.dart:109)
#3      main (file:///d:/a/farmr/farmr/farmr.dart:162)
<asynchronous suspension>

I think it will fix itself if I reboot. Is there any way I can fix it without rebooting?

**Comment by joaquimguimaraes** [comment]
I don’t think it will fix itself.
I suppose you created a blockchain template with an integer instead of a double
E.g.: replace `50` with `50.0` 
if it’s not that one of your blockchain files has a wrong format

**Comment by prodchia** [comment]
Ah. That makes sense. I changed the Major to Minor Multiplier in XCD from 1e9 to 1000000. I changed it to 1e6 and it has started working. Thank you
