### ISSUE TITLE
farmr crashes when any of the configured forks is not running

### ISSUE THREAD

**Issue by Feromrk** [joaquimguimaraes/farmr#118]
I have multiple chia forks running and all configured in farmr. If any of the forks is not running at all (e.g. by executing `flora stop all -d`) farmr can not be started:
```
Unable to detect running flora farming/harvesting service.
Unhandled exception:
Exception: Unable to detect running flora farming/harvesting service.
#0      Blockchain.initializePorts (package:farmr_client/blockchain.dart:202)
<asynchronous suspension>
#1      main (file:///home/runner/work/farmr/farmr/farmr.dart:166)
<asynchronous suspension>
```

Versions:
- farmr 1.7.5
- raspberry pi os 64 bit on rpi4

**Comment by joaquimguimaraes** [comment]
This is intended, it only happens when you start farmr and one of the forks is not running.
It will not crash if one of the forks crashes after it started collecting stats

**Comment by Feromrk** [comment]
I see, thanks for the explanation.
