### ISSUE TITLE
I updated to the latest version 1.7.5.6 and wasn't running stable for me

### ISSUE THREAD

**Issue by dutchietv** [joaquimguimaraes/farmr#126]
After a while the farmr bot says i lost connection. When i log in to my server all the forks are still online and farming. I closed the terminal and i got even 16 gb of ram back. Im not sure it is a issue of this latest version but i go back to 1.7.3 because that was stable for me.

This was a error i saw in the terminal 

(OS Error: Too many open files, errno = 24)

Platform: Linux

**Comment by joaquimguimaraes** [comment]
Were you running tsit?

**Comment by joaquimguimaraes** [comment]
This issue should be fixed in 1.7.5.7, let me know if it is as I'm not running as many forks as you.

**Comment by dutchietv** [comment]
> This issue should be fixed in 1.7.5.7, please let me know if it is as I'm not running as many forks as you.

Oke thanks for the feedback!

**Comment by dutchietv** [comment]
The latest version is certainly more stable. Only 1 issue i found so far it gives alers my farmers are offline but when i check them they are not offline, and still farming.

tested Version: v1.7.6.10
