### ISSUE TITLE
Mismatch of Last plot length info

### ISSUE THREAD

**Issue by PiSCaRGoT** [joaquimguimaraes/farmr#27]
I noticed the Last plot length duration is not the same as the actual creation time of the plot. I'm using Madmax windows plotter v0.0.5 and seeing random variations of the completion time reported by farmr. I'm also using hpool.exe

There are no log files to scan, so I'm assuming that you might be calculating the time from the plot filename datetime vs file last modified date, but it also seems like its a mismatch of that.

**Comment by joaquimguimaraes** [comment]
Hey, I have not really checked if the filenames match since I have not used madmax plotter yet. Can you give me an example of how they look?

**Comment by PiSCaRGoT** [comment]
Filename looks like this :
plot-k32-2021-06-16-11-08-0000000000ab6b6f36062db798a00000000000074fdcf4205007760000000000
Last Modified timestamp is : 
16/6/2021 11.35am
Farmr shows the length as 32mins, which if I calculate filename vs last modified, should be 27mins instead

**Comment by joaquimguimaraes** [comment]
Oh farmr includes copy times in plot length, mostly because you are not farming while its not copied to its destination.

**Comment by PiSCaRGoT** [comment]
I see, does that mean for hpool.exe, it calculates the time difference of :
(datetime in filename) vs (hpool recognition of the plot)?

I want to find a way to see if I can monitor the plot time creation length instead.

**Comment by joaquimguimaraes** [comment]
No, it works the same way for every mode, time difference between filesystem’s last modified date (after copied to destination drive) and filename.
Are you sure the time difference is 27 minutes?
Could it be picking up another field?

**Comment by PiSCaRGoT** [comment]
Ah, I think I've figured it out. I only change the last modified date in the plot file after the file copy is complete. If farmr scans the plotfile while still being transferred, the data is stored in farmr.cache, and won't get updated unless I flush the cache.

Just tested this and verified the above. I'll figure out a way around this from my end, since its a very niche requirement. Thanks again Joaquim and damn good work on the bot! I'm loving it.
