### ISSUE TITLE
[small Bug] When updating the size of incomplete plot, update the time modified as well. 

### ISSUE THREAD

**Issue by tinodj** [joaquimguimaraes/farmr#28]
This should be 

updateSizeAndEnd

https://github.com/joaquimguimaraes/farmr/blob/02b976fcd216767f8fe4afee8fd8aff1e860924e/lib/harvester/plots.dart#L105

and should do stat again and update the End field as well.

**Comment by joaquimguimaraes** [comment]
Hey, unfortunately Windows does not preserve timestamps when you copy files, and the code mentioned above only acts on cached plots (a plot which existed before). If the code did what you are suggesting then the plot lengths would be incorrect, since its completion date (modified date) would be many days later than its creation date. 
Does this make sense?

**Comment by tinodj** [comment]
Hey,

I am not sure that I understood the whole logic in the code but it seems to me that code logic at the moment is as following:

1. Check for a plot, if found, regardless of its size it will be added in the list and cached (imagine it is half copied). Time modified will be get at that point, and will be marked as incomplete.
2. Later, for this plot size will be updated, so it will become complete, but datetime modified will not be updated. So, the end time will be about (5-10mins off), depending how long a plot copy operation takes. 

But, yes, under windows if someone just copy some plot from one destination to another this will give trouble. So, either leave it as it is or do this update only if it is less than 15mins difference. But, anyway, this really doesn’t matter that much, it was just my OCDC in motion :D

**Comment by joaquimguimaraes** [comment]
This feature was implemented to preserve original timestamps of old plots rather than moving new plots. Copying/moving new plots shouldn't be an issue since chia only copies .tmp files and then renames them to .plot, not sure if mad max does this as well.

**Comment by tinodj** [comment]
Oh I see. But many people have some other scripts in place that are moving the completed(new) plots. For example: leave the plot on the disk where it was created and then move it later to a slower storage for farming. But I see, then a two step process (move to .tmp, then rename) will be a good workaround.
