### ISSUE TITLE
config.json resetting field values

### ISSUE THREAD

**Issue by Jaga-Telesin** [joaquimguimaraes/farmr#29]
The "Show Hardware Info" field is being overwritten on launch of farmer.exe (back to the default of 'true').  I've tried editing the field while the executable was running under Windows, and after closing farmer.exe out.  It reverts back to 'true' every time.

Do we need to lock the config.json file manually so fields don't reset?

**Comment by joaquimguimaraes** [comment]
Thank you for spotting this issue, it has been fixed in v1.4.0.4
<https://github.com/joaquimguimaraes/farmr/releases/tag/v1.4.0.4>

**Comment by Jaga-Telesin** [comment]
Thanks for the quick fix!
