### ISSUE TITLE
Forks

### ISSUE THREAD

**Issue by MinerGuy62** [joaquimguimaraes/farmr#35]
How would I add Forks to FARMR like Spare, Flax, etc?

**Comment by MinerGuy62** [comment]
Do I need to run a new Terminal for each one?

**Comment by MinerGuy62** [comment]
I figured out Flax and Chaingreen - what about Spare?

**Comment by joaquimguimaraes** [comment]
Template files for spare were not added because I do not endorse that crypto at all due to serious concerns about how their dev team operates.
You are free to create your own spare.json file, it will be displayed in farmr.net but it will not work in the discord bot.
Here's a template file to start with, adjust the paths to your installation:
```{
    "Binary Name": "spare",
    "Currency Symbol": "SPARE",
    "Minor Currency Symbol": "mojo",
    "Net": "mainnet",
    "Block Rewards": 4.0,
    "Blocks Per 10 Minutes": 32.0, 
    "Config Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\config",
    "Log Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\log"
}```

**Comment by miguelcarv1973** [comment]
chiarose json file

**Comment by miguelcarv1973** [comment]
> Template files for spare were not added because I do not endorse that crypto at all due to serious concerns about how their dev team operates.
> You are free to create your own spare.json file, it will be displayed in farmr.net but it will not work in the discord bot.
> Here's a template file to start with, adjust the paths to your installation:
> 
> ```json
> {
>     "Binary Name": "spare",
>     "Currency Symbol": "SPARE",
>     "Minor Currency Symbol": "mojo",
>     "Net": "mainnet",
>     "Block Rewards": 4.0,
>     "Blocks Per 10 Minutes": 32.0, 
>     "Config Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\config",
>     "Log Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\log"
> }
> ```

it says ID to long

**Comment by charnet3d** [comment]
> > Template files for spare were not added because I do not endorse that crypto at all due to serious concerns about how their dev team operates.
> > You are free to create your own spare.json file, it will be displayed in farmr.net but it will not work in the discord bot.
> > Here's a template file to start with, adjust the paths to your installation:
> > ```json
> > {
> >     "Binary Name": "spare",
> >     "Currency Symbol": "SPARE",
> >     "Minor Currency Symbol": "mojo",
> >     "Net": "mainnet",
> >     "Block Rewards": 4.0,
> >     "Blocks Per 10 Minutes": 32.0, 
> >     "Config Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\config",
> >     "Log Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\log"
> > }
> > ```
> 
> it says ID to long

You can change the currency symbol to SPR instead and it works: "Currency Symbol": "SPR".
The web interface should be updated to accept longer ids for currencies with longer symbols.

**Comment by miguelcarv1973** [comment]
Thank you

**Comment by Azyle66** [comment]
Issue with SPARE (I know...not supported) I have is:
"Unable to parse farmed SPARE. Is wallet service running?" error message and so wallet and such does not show up.
Fixable or?

**Comment by joaquimguimaraes** [comment]
> Issue with SPARE (I know...not supported) I have is:
> "Unable to parse farmed SPARE. Is wallet service running?" error message and so wallet and such does not show up.
> Fixable or?

The templates above have the wrong minor currency, it used to be mojo but they changed it to graviton.
Here's an updated working template:
```
{
    "Binary Name": "spare",
    "Currency Symbol": "SPARE",
    "Minor Currency Symbol": "graviton",
    "Net": "mainnet",
    "Block Rewards": 4.0,
    "Blocks Per 10 Minutes": 32.0, 
    "Config Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\config",
    "Log Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\log"
}
```

**Comment by Azyle66** [comment]
> 
> 
> > Issue with SPARE (I know...not supported) I have is:
> > "Unable to parse farmed SPARE. Is wallet service running?" error message and so wallet and such does not show up.
> > Fixable or?
> 
> The templates above have the wrong minor currency, it used to be mojo but they changed it to graviton.
> Here's an updated working template:
> 
> ```json
> {
>     "Binary Name": "spare",
>     "Currency Symbol": "SPARE",
>     "Minor Currency Symbol": "graviton",
>     "Net": "mainnet",
>     "Block Rewards": 4.0,
>     "Blocks Per 10 Minutes": 32.0, 
>     "Config Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\config",
>     "Log Path": "C:\\Users\\USER\\.spare-blockchain\\mainnet\\log"
> }
> ```

Tried this, but still same ""Unable to Parse" message...

**Comment by joaquimguimaraes** [comment]
Added goji and spare templates in v1.4.4.3
