### ISSUE TITLE
Install location

### ISSUE THREAD

**Issue by andymarden** [joaquimguimaraes/farmr#38]
The docs say it installs (Ubuntu 21.04) under ~/farmr but my install was under /etc/farmr

**Comment by joaquimguimaraes** [comment]
it will generate /home/user/.farmr directory after you first run ``farmr``

**Comment by andymarden** [comment]
Ok - I see now.
Suggest the readme in updated because it does not install there.
I saw it in /etc/farmr and thought - ah, that's where it is and edited the config file but it had not effect. Now I know why!
