### ISSUE TITLE
Don't working on macOS Catalina

### ISSUE THREAD

**Issue by sanok2000** [joaquimguimaraes/farmr#39]
![Bildschirmfoto 2021-06-23 um 13 19 47](https://user-images.githubusercontent.com/61139856/123088282-d6597f00-d425-11eb-9d47-71fcd34bdef0.png)

**Comment by joaquimguimaraes** [comment]
intel or m1?

**Comment by sanok2000** [comment]
Intel

**Comment by joaquimguimaraes** [comment]
Some users have been running it on macOS. Make sure that blockchain folder is in the project's path.

**Comment by sanok2000** [comment]
I found out that you need a path to the folder e.g. /Users/server/farmr/
Here at this point, then it works
![Bildschirmfoto 2021-06-27 um 09 56 06](https://user-images.githubusercontent.com/61139856/123537138-3efa7180-d72e-11eb-923c-5bd979a291c1.png)
I haven't been able to find the solution yet, because my Dart knowledge is not good.

**Comment by joaquimguimaraes** [comment]
That shouldn’t really be causing the issue

**Comment by joaquimguimaraes** [comment]
Did you extract every file from that .tar.gz? Make sure you extract “blockchain” folder

**Comment by sanok2000** [comment]
Yes, i did it.
![Bildschirmfoto 2021-06-27 um 10 09 50](https://user-images.githubusercontent.com/61139856/123537462-e330e800-d72f-11eb-9070-5eaf62d91ffd.png)

**Comment by sanok2000** [comment]
Found solution now:
Extract it to an empty folder than -> cd Folder (e.g. cd /Users/server/farmr) than start farmr (e.g /Users/server/farmr/farmer.sh)

Thanks, my mistake :)
