### ISSUE TITLE
Flax-Chg Cold wallets.

### ISSUE THREAD

**Issue by Puritosfaria** [joaquimguimaraes/farmr#42]
First of all thank you for this "tracker" is very useful to me.

There is a way to check the cold wallets for Flax-Chg like the chia one?¿ i tried adding the XHC cold wallet lines and changing the addes but didnt work.

**Comment by joaquimguimaraes** [comment]
flax cold wallet support was added in 1.4.3

**Comment by joaquimguimaraes** [comment]
support for chaingreen, seno, goji and spare cold wallets was introduced in v1.4.7
