### ISSUE TITLE
Farmer status: not available

### ISSUE THREAD

**Issue by Jaga-Telesin** [joaquimguimaraes/farmr#44]
Seeing the red text "Farmer status: not available" on the left side of the Farmr web display, but all of the statistics fill in just fine.  I double-checked the config file and the values/format seemed just fine.

Any suggestions as to why this might be happening?  I'm not using the Chia GUI for any plotting, that's coming from Swar (which I didn't configure for Farmr).  Essentially this rig is acting as a Farmer/Full node only while Swar runs in a Powershell separately.

**Comment by joaquimguimaraes** [comment]
This is the output of the cli command:
```chia farm summary```
You are most likely not farming chia.
Swar's Chia Plot Manager is a plot manager. It is not sufficient to farm chia.

**Comment by Jaga-Telesin** [comment]
Turns out it was an error in the config file - the GUI was still farming the entire time, passing challenges successfully.  I regenerated the config file fresh and re-added plot directories, and it's now reporting the farmer properly.
