### ISSUE TITLE
FLAX effort value 1158%

### ISSUE THREAD

**Issue by jmz-bit** [joaquimguimaraes/farmr#46]
I started farming Flax today on Ubuntu 20.04. For my farm statistic I'm using farmr app. This farmr app is fresh install. But I can see that my effort is 1158% and also it says that I won a block 18 days ago. But I started farming Flax today. Any idea what can be wrong?

**Comment by joaquimguimaraes** [comment]
Effort is bugged in farmr.net if you have not found a block.

**Comment by jmz-bit** [comment]
Thank you for answer. I started farming FLAX today with fresh install of FLAX app and FARMR app.

**Comment by joaquimguimaraes** [comment]
Most of this stuff has been rewritten since then. I believe it has been fixed. Feel free to reopen this issue if it has not.
