### ISSUE TITLE
Add syncing information to the dash board

### ISSUE THREAD

**Issue by xolutronic** [joaquimguimaraes/farmr#48]
First of all, thank you! Great tool, love it!

Show the farmer's peak height / blockchain height to help give visibility on the blockchain synchronization process.

**Comment by joaquimguimaraes** [comment]
Not sure how useful this would be given that it updates every 10 minutes

**Comment by xolutronic** [comment]
Well, depending on how long the node was offline, it could take longer than
10 minutes to get back to synced state.

Also, if the node is just syncing the blockchain from zero, it will take
several days to achieve this.

**Comment by joaquimguimaraes** [comment]
Oh I see what you mean then. Good suggestion.

**Comment by joaquimguimaraes** [comment]
![image](https://user-images.githubusercontent.com/82336674/125212867-1e8ef300-e2a8-11eb-81a5-586049e779c2.png)
This feature was been added in v1.5.0
