### ISSUE TITLE
Spare not working, unable to parse

### ISSUE THREAD

**Issue by Swamp64** [joaquimguimaraes/farmr#49]
First of all thanks for a fantastic tool!
Now I use it for XCH, XFX, CGN and SPARE. The first three run without issues. SPARE however reports:

_Unable` to parse farmed SPARE. Is wallet service running?
Unable to parse last height farmed for SPARE. Is wallet service running?_

I have my blockchain/spare.json file like this:

_{
    "Binary Name": "spare",
    "Folder Name": ".spare-blockchain",
    "Currency Symbol": "SPARE",
    "Minor Currency Symbol": "graviton",
    "Net": "mainnet",
    "Block Rewards": 4.0,
    "Blocks Per 10 Minutes": 32.0,
    "Config Path": "c:\\Users\\USER\\.spare-blockchain\\mainnet\\config",
    "Log Path": "c:\\Users\\USER\\.spare-blockchain\\mainnet\\log"
}_

...and my config/config-spare.json like this:

_[
    {
        "Name": "Farmer",
        "Currency": "USD",
        "Show Farmed SPARE": true,
        "Show Wallet Balance": false,
        "Show Hardware Info": true,
        "Block Notifications": true,
        "Plot Notifications": false,
        "Hard Drive Notifications": true,
        "Offline Notifications": false,
        "Farm Status Notifications": true,
        "Parse Logs": true,
        "Number of Discord Users": 1,
        "Public API": false,
        "Swar's Chia Plot Manager Path": ""
    }
]_

Any idea what I did wrong?

**Comment by joaquimguimaraes** [comment]
Hum, as of v1.4.4.3 you shouldn't need to set "Config Path" and "Log Path" for spare blockchain.
Does it run without that?
What's the output of ``spare wallet show``
