### ISSUE TITLE
Uneable to add SPARE (Id too long)

### ISSUE THREAD

**Issue by urufusaru** [joaquimguimaraes/farmr#50]
I got an "Id too long" error message when I try to add Spare to the monitor "cxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-spare" the erro message dissapear if I delete the last 2 characters from the ID "cxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-spa" but it doesn't add anything to the dashboard.

Thank you

**Comment by joaquimguimaraes** [comment]
This is a known bug. The only way to add it is through farmrBot (discord bot),
run the following command `` !chia link your-id-here ``

**Comment by joaquimguimaraes** [comment]
This has been fixed with the newest update of farmr.net
