### ISSUE TITLE
Suggestions for card to replace "Drives"

### ISSUE THREAD

**Issue by Qwinn1** [joaquimguimaraes/farmr#51]
First, thank you SO MUCH for this tool.  Tremendously useful.

So, on my system, with parsing enabled, I get a "Drives" card.  It only seems to see physical drives attached to the farmer for that count, though, but it does add up the space of all the plot directories I'm accessing via network shares for the "total of X tb" figure.  So, for example, mine says "6 drives, total of 443TB"  (I wish).  The "total of XTB" part is redundant with the "Plotted Space" card, and I don't see much utility in knowing how many physical drives are attached to just the farmer.

I think what would make more sense and be more useful is to replace this card with one called "Plot Directories".  It would look like this:

"PLOT DIRECTORIES
40/40 Directories Online
Total of 443TB" (again, this is redundant with Plotted Space, and I seem to get slightly different values, so just ditch it if you prefer)

As far as the "40/40 Directories Online", I would derive the second number by parsing the last "Searching Directories" entry in the log and counting the number of plot directories, and the first number by subtracting a count of any "WARNING  Directory: XXXXXXXXXXXX does not exist." entries that follow it.  So if, for example, I were to shut down one of my other network servers that has 10 plot directories on it, the card would show "30/40 Directories Online".

Whatcha think?

**Comment by Qwinn1** [comment]
Actually, slight modification as to how to grab the 30/40 example given above, so as to prevent issues where the last directory search isn't completed in the log yet, as they can take a bit of time:

1)  Find the last "Loaded a total of".
2)  Find the last "Searching directories" that precedes it for calculating the 40.
3)  Count the number of "WARNING   Directory:  XXXXXX does not exist" in between the two to know what to subtract from the 40 to get 30 online.

**Comment by joaquimguimaraes** [comment]
v1.5.0 was just released with a full list of drives
![image](https://user-images.githubusercontent.com/82336674/125212023-7296d900-e2a2-11eb-8eff-7f0adc860fd6.png)
I know this doesn't include everything you asked for. I still want to implement those features.
