### ISSUE TITLE
Cannot farm one fork and harvest for another on one machine simultaneously

### ISSUE THREAD

**Issue by Qwinn1** [joaquimguimaraes/farmr#52]
Hello,

So last night I switched from a network share model (one farmer/harvester accessing most plots via network share) to the harvester model (one farmer/harvester and 3 harvesters).  I was planning to have one of my plotters serve as farmer for chia and a separate server as the farmer for flax, and then each of these servers also acting as a harvester for the other fork.  

Unfortunately, farmr doesn't seem able to deal with this.  I tried running both "farmr" and "farmr harvester" on separate terminals on the server I'm trying to farm flax and harvest chia on, but this just confuses the heck out of it.  If I run just one, for example just "farmr", then adding the device results in it listed properly as a farmer under flax but as unable to get statistics under chia (and it also has the farmer symbol rather than the harvester symbol listed under chia).  If I run just "farmr harvester", then it lists as a harvester only under both flax and chia, but with errors such as on the network space card.

Thanks again for all your great work.  If I absolutely have to, I'll make one server the farmer for both, but I'm hoping there's a solution as it would be nice to not have to have all the logging for both on one server's desktop, and can instead dedicate the desktop of two different servers for each farming and monitoring a single fork.

**Comment by joaquimguimaraes** [comment]
There is a workaround for that, make 2 farmr folders, delete blockchain/xch.json from one of them and blockchain/xfx.json from the other. Then run harvester.exe from one folder and farmer.exe from the other

**Comment by Qwinn1** [comment]
Thanks, I will try that.  One question - I did that for the .farmr directory that is under my user directory, but I'm not sure where the folder with the actual Ubuntu versions of harvester.exe is.  I do find a "farmr" in /usr/bin which I assume is what runs when I enter farmr at the command line with no path.  Not sure where the .deb process installed them, Any idea where I might find the folder with an actual harvester executable in order to try what you suggested?  Or a way to just run farmr and specify which of my .farmr directories to use for the .jsons.

**Comment by Qwinn1** [comment]
So at least for right now, it looks like I got it working under Ubuntu.  Basically, have only the .json file active for the farmer in the blockchain directory as you described.  Run farmr in a terminal - it will only send farmer messages for the fork that had the active json.  Then open a new terminal, switch the active .json to the one that you are harvesting on the same machine, and then run farmr harvester.  

I am assuming this works because, once a farmr or farmr harvester session is started, neither will ever re-read the json files.  The json files are only read upon initial run.  So you can fire one up for the farmer in one terminal, and once it's running you can reconfigure it for running farmr harvester without messing up the farmr session that is already running.

Solid workaround, but it's rather a pain to make work with multiple steps, and it'd be hard to script (at least for me) in a way that fires up separate terminals to run each process without their being closed or in the background.  So consider this a request for a more elegant solution in the next version.  Thanks again for your great tool and for your help!

**Comment by joaquimguimaraes** [comment]
This can be simplified by extracting the "Other Linux" .tar.gz files into separate folders
https://github.com/joaquimguimaraes/farmr/blob/main/docs/installation-linux.md
These are self-contained

**Comment by Qwinn1** [comment]
That version is indeed MUCH easier to work with.  Had no trouble at all overcoming the problem I described in my OP.  Consider this request closed, and thanks again!

**Comment by joaquimguimaraes** [comment]
Easier to work with, harder to upgrade. The .deb is better for most inexperienced users imo
