### ISSUE TITLE
Flax info not picked up on farmr

### ISSUE THREAD

**Issue by Stevengen** [joaquimguimaraes/farmr#54]
farmer.exe is picking up and reporting flax statistics, but the generated ID, when entered into farmr is being rejected. Farmr looks like it wants to add, then the screen comes back up with XCH, CGN, etc, but no XFX. Edit resolved on its own overnight.

**Comment by urufusaru** [comment]
Same for me, only generating ID's for chia

**Comment by joaquimguimaraes** [comment]
Follow this guide if you want to activate flax
https://github.com/joaquimguimaraes/farmr/blob/main/docs/forks.md

**Comment by urufusaru** [comment]
Thank you, I think I'll stay on v.1.4.6 for now. Forks work well for me there.
