### ISSUE TITLE
Frequent Discord login authorization required (every 2-3 hours)

### ISSUE THREAD

**Issue by PiSCaRGoT** [joaquimguimaraes/farmr#56]
Not sure if this is the intended behavior, but it keeps prompting the Discord login authorization every 2-3 hours.

Just wondering if it could be a setting that I overlooked, or any other way to stay logged on, especially when the browser is left open?

**Comment by joaquimguimaraes** [comment]
No, this is an issue. Trying to get it fixed.

**Comment by joaquimguimaraes** [comment]
This has been fixed with the newest farmr.net update
The authentication system has been rewritten and it's client-based now.
