### ISSUE TITLE
Enhancement: restart harvester if connection error

### ISSUE THREAD

**Issue by stanchiam** [joaquimguimaraes/farmr#60]
Will be good if farmr can help run chia/xxxxx  start harvester -r when 
"Connection error. Check if harvester is running at xxxxx" occurs

And also send a notice/alert

**Comment by joaquimguimaraes** [comment]
Restarting services remotely is something I am not willing to implement, due to potential security issues.
However, farmr can currently tell you and notify you if your harvesters are running and finding filters if ``Parse Logs`` is enabled.
This setting will be enabled by default from v1.5.0
