### ISSUE TITLE
Hpool config.yaml

### ISSUE THREAD

**Issue by diowil** [joaquimguimaraes/farmr#63]
hpool.exe under windows
Cannot open file, path = 'config.yaml'
In my config-xch.json I have ""HPool Directory": "C:\\Users\\blabla\\Chia\\Hpool\\miner",
but it doesn't work
Oh no! Something went wrong.
FileSystemException: Cannot open file, path = 'config.yaml' (OS Error: The system cannot find the file specified.
, errno = 2)
Do NOT close this window.

It worked with previous version (1.4 ...)

**Comment by joaquimguimaraes** [comment]
Hey, I was made aware of this bug some minutes ago.
It seems that HPool mode is incompatible with the new online config system.
Please set "Online Config" in blockchain/xch.json to false and restart the client, this will load local config again

**Comment by diowil** [comment]
Ok. Client now works but it is not visible on farmr.net and farmrbot says: 
Error: Farmer not found.
No clients found! Find out how you can install farmr client in your farmer/harvester in #⬇│downloads

**Comment by joaquimguimaraes** [comment]
Are you not able to link it?

**Comment by joaquimguimaraes** [comment]
v1.5.0.2 forces local configuration files in HPool Mode, which solves this issue

**Comment by diowil** [comment]
Yes it is working now. It did not work at the beginning but after deleting cache file and adding new generated id to farmr.net it started to work. Thank you.

**Comment by diowil** [comment]
Thanks
