### ISSUE TITLE
Enhancement:  Please add Chia/Flax/OtherFork version # to the Version card

### ISSUE THREAD

**Issue by Qwinn1** [joaquimguimaraes/farmr#65]
Your Version card currently shows only the version number for Farmr. Please add the Chia/Flax version # installed on that harvester/farmer as well.  I have no idea how to actually query for that myself - even in the Gui, selecting "About Chia" doesn't display the version #. With all the 1.2.0 / 1.2.1 and more versions coming out rapidly and having to update one by one, it'd be handy to have Farmr confirm the update worked.

**Comment by joaquimguimaraes** [comment]
![image](https://user-images.githubusercontent.com/82336674/125694343-a11b084b-0995-4691-aa9c-1fdd2becfb5a.png)
This has been added in v1.5.2, currently testing this version in dev.farmr.net with some other changes

**Comment by Qwinn1** [comment]
Could it be added to the existing Version card instead of another card?  Minor quibble, just happy to see it at all, just figured merging them would be a better use of screen space.  Something like:

VERSION
Farmr:  1.5.2
Blockchain:  1.2.0

**Comment by joaquimguimaraes** [comment]
sure, I can update the website with that

**Comment by Qwinn1** [comment]
Updated to 1.5.3 and I can report this is working great!  At least on the Farm/Farmer tabs.  Don't worry about merging the cards if it's annoying, sure you're busy.  But is there a way to also know the version # of the software installed on the harvesters as well?  The version that's running when you run "chia start harvester -r" from the CLI anyway.

**Comment by joaquimguimaraes** [comment]
Merging the cards would imply changing their format a bit, so I'll leave it for another time.
I was about to say that harvesters didn't require chia binary path, but you just reminded me that "chia start harvester -r" was introduced in v1.5.0, so yes it makes sense that harvesters also display their version.
I've appllied these changes and they will be released in v1.5.3.2 in a couple of minutes

**Comment by Qwinn1** [comment]
Working great, thank you!

(And really glad I asked... lol... I've only updated 3 Flax harvesters so far and I've got 0.1.1dev0 on the farmer, 0.1 on one harvester, 0.1.0 on the second harvester... wonder what the difference between those last two is!  Almost afraid to check the fourth....)
