### ISSUE TITLE
Crash with 1.5.1.1

### ISSUE THREAD

**Issue by kmoore134** [joaquimguimaraes/farmr#66]
Starting up ./farmer.sh and backgrounding it with &. Seeing it fail shortly after with the following:

```
Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<String>'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:46)
#1      Prompter.prompt.<anonymous closure>.<anonymous closure> (package:console/src/prompt.dart:222)
#2      new Future.<anonymous closure> (dart:async/future.dart:174)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

**Comment by joaquimguimaraes** [comment]
This is a ``console`` library exception, it happens when it can't detect user input. There's not much I can do about it.
I've added a headless mode because of that, you can run ``./farmr headless`` to start it in headless mode
I'll add this to documentation soon

**Comment by w4d3j** [comment]
Getting the same crash and error with the command `nohup /usr/bin/farmr -c 'harvester headless' &`

**Comment by joaquimguimaraes** [comment]
> Getting the same crash and error with the command `nohup /usr/bin/farmr -c 'harvester headless' &`
> aarch64/RPi .deb pkg

I was not able to recreate this issue. Make sure you are running version 1.5.1.1 and not 1.5.1

**Comment by kmoore134** [comment]
Confirmed this seems to be working in headless mode for 1.5.2.1
