### ISSUE TITLE
Enhancement:  Either add or replace Farm "Last Update" with "Oldest Update"

### ISSUE THREAD

**Issue by Qwinn1** [joaquimguimaraes/farmr#67]
I have 4 harvesters.  In the last version, you added the "Last Update" card to the Farm, listing the most recent update received by Farmr from those harvesters.  This seems less useful information than "Oldest Update" would be... meaning, if I have Farmr properly running on only one of my harvesters, "Last Update" would never indicate to me that there was a problem on the other 3.  If one of the Farmr terminal processes crashed or was accidentally cancelled or still on a previous version that wasn't updating properly or whatever, the "Oldest Update" running beyond 20 minutes would tell me that I need to take a look at the individual harvesters and find out which one isn't sending updates as needed.

(Doesn't have to be "Oldest Update", btw, I just can't think of a better wording for the label yet.  "Stalest Update", maybe?)

Haven't had time to update to 1.5.2.1 yet but looking forward to doing so tonight!  Thanks again for all your great work.

**Comment by joaquimguimaraes** [comment]
I think this is important, so I won’t close it yet.

**Comment by joaquimguimaraes** [comment]
![image](https://user-images.githubusercontent.com/82336674/129457303-8e70db21-38d5-4a31-b8c8-3e8e69fd56d0.png)

This feature has been implemented and it's live in farmr.net
