### ISSUE TITLE
Bug:  "Do not close this window." spam on Windows command session

### ISSUE THREAD

**Issue by Qwinn1** [joaquimguimaraes/farmr#68]
(I had noted this in the 1.5.0 issues thread but wasn't sure if you saw it since it was unresolved in 1.5.3.4, so making it its own issue.)

Minor issue report, started when the new "1) View xch report" menu was added and still there: On my Windows harvester, in the open command box that you have to leave running for farmr to work, it keeps sending "Do NOT close this window." over and over again, This happens twice as soon as I fire farmr up (I presume because I'm sending harvester reports for both chia and flax), and then twice again every so often with each data send. Repeated "Do NOT close this window."s will eventually scroll the new menu options off the screen completely. It doesn't behave this way in Ubuntu - there, it just stays on the new menu.

**Comment by joaquimguimaraes** [comment]
This was fixed in v1.6.0
