### ISSUE TITLE
Feedback 1.6.1

### ISSUE THREAD

**Issue by Qwinn1** [joaquimguimaraes/farmr#71]
Hullo!  Love the new Overview.  Great addition.  Unfortunately I can't help you with the pool stuff as I am and will continue to be pure OG (which will at least keep me using forks).

Two issues so far:

1)  In the Overview, Avg Response is showing up as 0.00s.  That said, having Longest Response there would be more useful.  With that I probably wouldn't even need to look below the Overview unless it showed a problem.  Actually, no, it'd have to have cold wallet balance on it too for that.

2)  My chia "last block x days ago" is fine, but my Flax one broke.  Earlier today it said "last block 1 day ago", which is correct.  After updating to 1.6.1, it now says "last block 9 days ago".  Nine days ago happens to be precisely when I won my last block on my hot wallet, after which I switched everything over to a cold wallet.  So it *seems* like it's no longer reading the last block based on my cold wallet and somehow switched back to checking last block on my old wallet.  Hope that gives you a good hint of what might've gone wrong there.  And I'll just reiterate once more here (since it's relevant) that, at least for solo farming, "proof found" by harvester would be more useful to me than wallet-based blocks found.  I get that that might be useless for pools though, as I'm aware that the log spits out tons of "proof founds" when pooling.

**Comment by joaquimguimaraes** [comment]
Yes, apparently there was a bug with effort in FlaxExplorer cold wallets, you spot these bugs so quickly!
This was fixed in commit e6c7db9d807072bab1a62c06c5cf6a83bff0350a and will be released in v1.6.1.1

Chia logs can't tell the difference between pool partial proofs and solo proofs, so its not possible to implement something based on proofs.

**Comment by joaquimguimaraes** [comment]
I just added maximum response times to the overview table

**Comment by Qwinn1** [comment]
Nice on both counts!  Thank you!  I really like that you added Effort to it too... that eliminates the need to have Wallet Balance up there, since you'll know if you hit a block by the effort dropping.

**Comment by Qwinn1** [comment]
On this issue:

"Chia logs can't tell the difference between pool partial proofs and solo proofs, so its not possible to implement something based on proofs."

Could this be a configurable option, maybe?  I don't know if YOU have any other way to tell if pools are in play, but, even if you couldn't, the user will know.  If you're using pools, the info on a Proofs Found card wouldn't really be useful, but those people could always disable/remove the card, while it still being very useful to solo farmers.

(Another reason I haven't mentioned until now for it, by the way is, it IS possible to find a proof but not get a block reward.  My very first Flax proof did that.  If that happened again, I'd want to know about it, but currently have no way other than digging through logs manually).

**Comment by Qwinn1** [comment]
Very minor bug, and I think the bug lies with Flax, not with Farmr, but Farmr could account for it.  

From my observations, I get the impression that the Farm tab will only have a Blockchain card if the Blockchain of every farmer and harvester for that blockchain is identical, which makes absolute sense.  Unfortunately, for some odd reason, in Windows running "flax version" returns 0.1 whereas on Linux it returns 0.1.0, even though the Windows version IS also 0.1.0 per the directory structure.  Don't know if you feel it's worth putting in exception code to handle that or not, but thought you'd like to be aware.

**Comment by joaquimguimaraes** [comment]
Regarding your previous remark, it is not possible to say if certain proofs were from nft plots or og plots, so afaik its impossible to tell them apart in the logs.

Also, I don't think there's anything I can do about how each blockchain versions its clients. Even chia can't nail versioning after so many releases. There are some final releases with "dev" in the version string and so on

**Comment by Qwinn1** [comment]
Thanks for the response.

"Regarding your previous remark, it is not possible to say if certain proofs were from nft plots or og plots, so afaik its impossible to tell them apart in the logs."

Yes, I know.  I get that it wouldn't be useful to anyone using nft plots.  I just happen to be one of those people who is only using OG plots and never intends on pooling.  :) 

Fair enough on the versioning.

**Comment by joaquimguimaraes** [comment]
I believe these have been fixed
