### ISSUE TITLE
How I use SpacePool Wallet?

### ISSUE THREAD

**Issue by Keikunbr** [joaquimguimaraes/farmr#73]
In Farmr.net Configuration->SpacePool Public Keys I need to put my Pool Public Key or my SpacePool Wallet Address or SpacePool Id?

**Comment by joaquimguimaraes** [comment]
Hey, these are pool public keys (or launcher_id) I believe.

**Comment by Keikunbr** [comment]
> 
> 
> Hey, these are pool public keys (or launcher_id) I believe.

It's laucher Id. But Farmr.net show "HPool" instead off "Spacepool" in "Status".

**Comment by joaquimguimaraes** [comment]
Are you launching it in hpool mode? Don't open hpool.sh/hpool.exe, keep using farmer.sh/farmer.exe as you need a full node to farm spacepool

**Comment by Keikunbr** [comment]
> 
> 
> Are you launching it in hpool mode? Don't open hpool.sh/hpool.exe, keep using farmer.sh/farmer.exe as you need a full node to farm spacepool

I was using harvester.exe instead of farmer.exe. Farmr.net It's OK now. Thanks.
