### ISSUE TITLE
Unable to compile from source

### ISSUE THREAD

**Issue by doobran** [joaquimguimaraes/farmr#75]
user@user:~/farmr$ dart pub get
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to report feature usage statistics     ║
  ║ and to send basic crash reports. This data is used to help improve the     ║
  ║ Dart platform and tools over time.                                         ║
  ║                                                                            ║
  ║ To disable reporting of analytics, run:                                    ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Resolving dependencies...
Could not find a file named "pubspec.yaml" in "/home/user/farmr/lib/system_info".
user@user:~/farmr$ dart run environment_config:generate;
Resolving dependencies...
Could not find a file named "pubspec.yaml" in "/home/user/farmr/lib/system_info".

if you copy pubspec.yaml to "/home/user/farmr/lib/system_info". You get:

user@user:~$ cd farmr/
user@user:~/farmr$ dart pub get;
Resolving dependencies...
Error on line 1, column 7 of lib/system_info/pubspec.yaml: "name" field doesn't match expected name "system_info".
  ╷
1 │ name: farmr_client
  │       ^^^^^^^^^^^^
  ╵
user@user:~/farmr$

**Comment by joaquimguimaraes** [comment]
One of the dependencies is a git submodule. You need to clone the repo with ``--recurse-submodules`` in order to download all git submodules.
so the command becomes:
``` git clone --recurse-submodules https://github.com/joaquimguimaraes/farmr.git ```
Or you can download each release's source.zip (as per the instructions in documentation)

**Comment by joaquimguimaraes** [comment]
This issue was fixed in Dart's GitHub Action @dart-lang/setup-dart issue https://github.com/dart-lang/setup-dart/issues/32
I've removed system_info git submodule, so compiling from source doesn't need ``--recurse-submodules`` anymore.
