### ISSUE TITLE
incorrect status

### ISSUE THREAD

**Issue by w4d3j** [joaquimguimaraes/farmr#76]
I just updated my harvester to 1.6.3, and after I entered my "launcher ID" for Space Pool (public key), the first square on my harvester's dashboard now says "Status: HPool" where it used to say "Status: Farming".  On my primary farmer, which is still on version 1.6.2.5, it says "Status: Farming" using the same public key.

**Comment by joaquimguimaraes** [comment]
“Status: HPool” is what it would show if you were running farmr client in HPool mode (``hpool.sh`` or ``hpool.exe``) 
this is not what you should be doing if you’re running a harvester. Please confirm that youre running farmr client in harvester mode ( ``harvester.sh`` or ``harvester.exe`` )

**Comment by w4d3j** [comment]
I installed via the .deb package (aarch64 on raspberry pi 4). The program was called via the same script I've been using for weeks: 
`harvest(){`
    `source "${HOME}"/chia-blockchain/venv/bin/activate`
    `chia start -r harvester`
    `nohup farmr harvester headless &`
`}`

Adding "headless" when the mode was introduced is the only modification I've made.

![image](https://user-images.githubusercontent.com/4414148/127370876-ea9bfea9-03b7-4536-8b56-963bafb6dd14.png)

**Comment by joaquimguimaraes** [comment]
Oh, that's troublesome. The .deb package must have gotten the wrong mode somehow! I'll have a look

**Comment by joaquimguimaraes** [comment]
I just installed the aarch64 .deb on my raspberry pi and it shows up as a harvester (and Harvesting)
I think you're seeing a very weird issue. Can you message me in discord? I'll guide you on how you can launch farmr.net in debug mode so I can recreate your situation and hopefully get it fixed.

**Comment by w4d3j** [comment]
Will do.  I'm on my way out the door, but I'll hop on Discord after work.

**Comment by joaquimguimaraes** [comment]
Closing this issue as we figured out the main cause and the fix is now live in farmr.net
