### ISSUE TITLE
Feedback 1.6.3

### ISSUE THREAD

**Issue by Qwinn1** [joaquimguimaraes/farmr#79]
Hello!  I'm back with more annoying suggestions.  Loving where things are but I see a few areas for small improvement that I figured I'd share.

1)  Overall, the new overview is absolutely awesome.  One very very cool enhancement would be:  when you click on a particular line/blockchain in the overview right now, it blinks but doesn't do anything else.  It would be great if clicking a line made the cards below switch to the Farm tab for that particular blockchain.  Bonus points for scrolling the left vertical bar so that Farm was on top so the user would have access to click on the Farmer/Harvesters beneath it.

2)  The sort order of the overview changes on every refresh.  Making it a static order would be better - bonus points for stickying XCH as the first line and letting the rest of the lines go alphabetically by symbol beneath it.

3)  The Farmed column in the Overview is useless if you're using Cold Wallets (which everyone should be).  If you need room in the overview for anything, I'd ditch that one first.  If I got to pick, I'd replace it with Wallet Balance (Cold if one is specified, hot otherwise).

4)  In the overview, CGN actually goes into scientific notation in the EDV column for me!  My EDV is 1.4e+3 CGN.  Dunno if that was deliberate but figured it's possible you only see that with a large enough farm and you might not be aware of it.

Everything else about the Overview is fantastic!  The next issue is about both the Overview and the cards below, and is more important than any of the above in my view.

5)  Please refine both the Overview line "ETW" and the ETW card below to be more specific and permit displaying hours, not just days.  Right now, my ETW for DogeChia is 4 hours per the GUI.  It displays as 0 days on the card and 0.2d on the Overview line (yes, right now, the Overview gives more detail than the large Card, and the standard blockchain GUIs are more specific than either.  Can't have that!)  It's particularly important because some blockchains, such as HDDCoin, are still on an old enough version of the software where plots from harvesters are not correctly summed on the GUI and only show the ETW based on the plots directly on the farmer.  The HDD Coin GUI only shows 25% of my plots and claims an ETW of 14 hours based on that, while Farmr shows 0 days on the card and 0.2d in the overview... I know the real number *should* be somewhere around 3 or 4 hours, but I actually can't determine that from the GUI *or* Farmr atm.

Thanks for all your help!  This is already hands down the best Chia/Fork monitor available anywhere, far as I'm concerned.  Saved me countless hours already.

**Comment by joaquimguimaraes** [comment]
1. Would be a good idea, but it's not exactly easy to achieve, so I'll do it later
2. and 3. are very good suggestions and they've been implemented in the development version of the website, which will be released with 1.7.0
4. it's not intended, its just the way dart (and python) handle some large numbers, chia also shows it that way in some cases, so i'll leave it as it is
5. Yes this has to be done, I'm not sure It will be ready by next release.

**Comment by joaquimguimaraes** [comment]
Ok I think I implemented 5 in latest dev.farmr.net but I am not sure

**Comment by joaquimguimaraes** [comment]
Closing this as all features were implemented except 1.
Will reopen if/when necessary.
