### ISSUE TITLE
Chia - no cold wallet data

### ISSUE THREAD

**Issue by jmz-bit** [joaquimguimaraes/farmr#82]
I'm using farmr app 1.6.3.7 on Ubuntu 20.04. 

Cold wallet for XFX and XFL is working without any problems. But for Chia XCH this is not working.

Cold wallet addreses are in config files in farmr folder. 3 config files XCH, XFX, XFL.

On my Windows computer I'm using farmr.net webpage the cold wallets addresses are also entered for each farm XCH, XFX, XFL. 

Chia wallet is OK I can check XCH ammount using Chia explorer and everything is fine there.

**Comment by joaquimguimaraes** [comment]
chiaexplorer api stopped working overnight, this will be fixed in a release later today.

**Comment by jmz-bit** [comment]
> chiaexplorer api stopped working overnight, this will be fixed in a release later today.

Thank you for quick answer. Do I have to do anything with farmr app ? or just wait until this will work?

**Comment by joaquimguimaraes** [comment]
This has been fixed in v1.7.0, unfortunately you need to update the client

**Comment by jmz-bit** [comment]
> This has been fixed in v1.7.0, unfortunately you need to update the client

OK. Thank you!
