### ISSUE TITLE
Avast detect farmr.exe as a virus

### ISSUE THREAD

**Issue by Keikunbr** [joaquimguimaraes/farmr#86]
My antivirus Avast detect file farmr.exe as a virus (with EvoGen ???) and deleted it.

**Comment by joaquimguimaraes** [comment]
It's a false alarm. The code is open-source and compiled by a GitHub action. It's also signed with my GPG key.
It's okay if you don't trust me, you can check the code or ask someone who's reviewed it.
You can also compile it from source.
https://github.com/joaquimguimaraes/farmr/blob/main/docs/installation-source.md

**Comment by Keikunbr** [comment]
I know it's a false positive. I sent file farmr.exe to Avast reporting this issue.
Thanks for the feedback.

**Comment by joaquimguimaraes** [comment]
Thank you
