### ISSUE TITLE
Chia cold wallet is not working again.

### ISSUE THREAD

**Issue by jmz-bit** [joaquimguimaraes/farmr#87]
I reported this error a few days ago.

It was warking since a new ver of the farmr app was released.

But stopped working again today morning.

Other forks are working fine and farmr app is showing the cold wallets value.

**Comment by Qwinn1** [comment]
That was fixed in the version released this morning, 1.7.1.

**Comment by jmz-bit** [comment]
> That was fixed in the version released this morning, 1.7.1.

Sorry I missed that information. I will update the app. Thank you.

**Comment by joaquimguimaraes** [comment]
Really sorry about this. Was not expecting it to happen twice this week! 
there’s nothing I can do when these third party services change
it’s no longer using chiaexplorer for cold wallets, it’s using alltheblocks now

**Comment by jmz-bit** [comment]
> Really sorry about this. Was not expecting it to happen twice this week!
> there’s nothing I can do when these third party services change
> it’s no longer using chiaexplorer for cold wallets, it’s using alltheblocks now

It is not your fault. I understand that you are using third party service.
I updated the app to 1.7.1 and now is working OK. Thank you.
