### ISSUE TITLE
Add more decimal digits in overview

### ISSUE THREAD

**Issue by prodchia** [joaquimguimaraes/farmr#94]
With NFT farmer reward of 0.25, the farmed column in overview doesn't show the right number. I believe it is rounding it to the nearest integer. May be add two decimal digits to handle 0.25.

**Comment by joaquimguimaraes** [comment]
Good suggestion, this is now live in farmr.net

![image](https://user-images.githubusercontent.com/82336674/129457253-de769ed8-f494-46d7-9871-3426f34182c6.png)

**Comment by shawnli87** [comment]
The Wallet column could use the same change. Right now the rounding can be misleading.
