### ISSUE TITLE
Number of harvesters on farmr.net

### ISSUE THREAD

**Issue by ShurikMMS** [joaquimguimaraes/farmr#96]
Please add the total number of harvesters online / offline
The number of combines is growing;) it is inconvenient to leaf through the column on the left, and remember how many of them there should be

**Comment by joaquimguimaraes** [comment]
![image](https://user-images.githubusercontent.com/82336674/129457229-c3533fbe-901a-4713-bae6-4b2f103082a4.png)
This has been added and should be live in farmr.net

**Comment by ShurikMMS** [comment]
Thanks
