### ISSUE TITLE
Cold wallets problem.

### ISSUE THREAD

**Issue by jmz-bit** [joaquimguimaraes/farmr#98]
I'm using farmr app 1.7.1.1. Today afternoon 15th August some cold wallets are not working.

So far only Flax is working.

Chia, Flora, DogeChia are not working.

I changed nothing in my system... it just stopped working today.

**Comment by joaquimguimaraes** [comment]
Those cold wallets are provided by AllTheBlocks.net

The website was down for a couple of hours but it should be back online.

**Comment by jmz-bit** [comment]
> Those cold wallets are provided by AllTheBlocks.net
> 
> The website was down for a couple of hours but it should be back online.

It is working now again. Thank you for the informations.
